runtime: nodejs16

handlers:
  - url: /(.*\.(gif|png|jpg|js|css|ico))$
    static_files: build/\1
    upload: build/(.*\.(gif|png|jpg|js|css|ico))$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
